FROM ubuntu:18.04
RUN apt-get update; apt-get upgrade -y
RUN apt-get install -y curl jq vim openssh-client
RUN apt-get install -y iperf
RUN apt-get install librdkafka-dev

# set base image (host OS)
FROM python:3.8

COPY /src /app

WORKDIR /app

COPY ../requirements.txt .

RUN pip install -r requirements.txt

EXPOSE 8080

ENTRYPOINT [ "python" ]

CMD [ "./lmpolicyformsource.py" ]
