FROM ubuntu:18.04
RUN apt-get update; apt-get upgrade -y
RUN apt-get install -y curl jq vim openssh-client
RUN apt-get install -y iperf

# set base image (host OS)
FROM python:3.8

# set the working directory in the container
WORKDIR /code

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# copy the content of the local src directory to the working directory
COPY src/ .

# command to run on container start
CMD [ "python", "./servicecloudevent.py" ]
