# Use the official lightweight Python image.
# https://hub.docker.com/_/python
FROM python:3.7-slim

# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

# Copy local code to the container image.
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . /app

RUN pip install -r requirements.txt

CMD ["/app/lmpolicycapture.py"]
ENTRYPOINT ["python"]
